version: "3.9"

services:
  kairosdigital-api:
    image: node:20-alpine
    container_name: kairosdigital-api
    restart: unless-stopped
    working_dir: /app
    networks:
      - kairos_net
      - evogo_net
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.kairosdigital-api-web.rule=Host(`api.kairosk.fbautomacao.space`)
      - traefik.http.routers.kairosdigital-api-web.entrypoints=web
      - traefik.http.services.kairosdigital-api-web.loadbalancer.server.port=3001
      - traefik.http.routers.kairosdigital-api-websecure.rule=Host(`api.kairosk.fbautomacao.space`)
      - traefik.http.routers.kairosdigital-api-websecure.entrypoints=websecure
      - traefik.http.services.kairosdigital-api-websecure.loadbalancer.server.port=3001
      - traefik.http.routers.kairosdigital-api-websecure.tls.certresolver=letsencrypt

  kairosdigital-frontend:
    image: node:20-alpine
    container_name: kairosdigital-frontend
    restart: unless-stopped
    working_dir: /app
    networks:
      - kairos_net
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.kairosdigital-frontend-web.rule=Host(`crm.kairosk.fbautomacao.space`)
      - traefik.http.routers.kairosdigital-frontend-web.entrypoints=web
      - traefik.http.services.kairosdigital-frontend-web.loadbalancer.server.port=3000
      - traefik.http.routers.kairosdigital-frontend-websecure.rule=Host(`crm.kairosk.fbautomacao.space`)
      - traefik.http.routers.kairosdigital-frontend-websecure.entrypoints=websecure
      - traefik.http.services.kairosdigital-frontend-websecure.loadbalancer.server.port=3000
      - traefik.http.routers.kairosdigital-frontend-websecure.tls.certresolver=letsencrypt

volumes:
  postgres_data:
  redis_data:

networks:
  kairos_net:
    driver: bridge
  evogo_net:
    external: true
    name: evogo_evogo-network
  dokploy-network:
    external: true
